name: Kotlin Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   ktlint:
     runs-on: ubuntu-latest
     steps:
       - name: "checkout"
         uses: actions/checkout@v2
         
       - name: "ktlint"
         uses: "vroy/gha-kotlin-linter@v1"
